### ISSUE TITLE
Not recording/tracking purchase data

### ISSUE THREAD

**Issue by nemoryoliver** [qonversion/flutter-sdk#10]
Hi Team,

It's my first time using your package. I know it's in beta. But I still used it when I launched a new version of my app. But unfortunately, it is not able to track/record purchases as I cannot see any purchases in the web dashboard. 

Still, I am very excited to see this beat RevenueCat since it looks a lot more promising and not to mention the awesome pricing!

Thank you very much

**Comment by iVirn** [comment]
Hi Oliver! 

> it is not able to track/record purchases as I cannot see any purchases in the web dashboard.

Please, help us to investigate this problem. 

Did you experience this issue on iOS/Android only or you support both platforms with your app?
At what point of your app lifecycle do you initialize Qonversion? 
Which Qonversion SDK method do you use to initialize Qonversion (1st, 2nd or 3rd as described [here](https://github.com/qonversion/flutter-sdk#usage))?

It would really help us to find out what is the problem and fix it ASAP. 

Thanks for reporting!

**Comment by iVirn** [comment]
> Present: launchWithAutoTrackPurchases

Hi again. 
Sorry for being late as well. 
We've just publish version 0.3.0 with API update, you can now use `launch` method to initialize Qonversion; all other methods have been deprecated. 
Please, try to update your SDK version and use new `launch` method to init Qonversion, we believe it should resolve existing problem.

**Comment by nemoryoliver** [comment]
> > Present: launchWithAutoTrackPurchases
> 
> Hi again.
> Sorry for being late as well.
> We've just published version 0.3.0 with API update, you can now use `launch` method to initialize Qonversion; all other methods have been deprecated.
> Please, try to update your SDK version and use new `launch` method to init Qonversion, we believe it should resolve existing problem.

Great to hear! Thank you for your continued support to this package!

**Comment by iVirn** [comment]
@nemoryoliver hello again! 
We've just published release 1.0 with Android fix on purchase tracking. 
On Android you must call `Qonversion.trackPurchase(skuDetails, purchase)` method on each purchase success in order to track purchases since there are different `BillingClient`s in Android in iAP libraries in Flutter and in Qonversion with autrotracking enabled. 

So please use `trackPurchase` method if `Platform.isAndroid` and everything should work correctly.

**Comment by nemoryoliver** [comment]
> @nemoryoliver hello again!
> We've just published release 1.0 with Android fix on purchase tracking.
> On Android you must call `Qonversion.trackPurchase(skuDetails, purchase)` method on each purchase success in order to track purchases since there are different `BillingClient`s in Android in iAP libraries in Flutter and in Qonversion with autrotracking enabled.
> 
> So please use `trackPurchase` method if `Platform.isAndroid` and everything should work correctly.

Thanks a lot! I'm just waiting for you to fully compete with RevenueCat by implementing your own purchase system.
