### ISSUE TITLE
skuDetails is null 

### ISSUE THREAD

**Issue by samatzhusup** [qonversion/flutter-sdk#117]
i showing skuDetails is null 

App pushlised Play Market
also i showing prettyPrice null

![2021-09-24_16-43-21](https://user-images.githubusercontent.com/50781959/134662212-7a82c82d-f1cf-4704-98c5-89f8ba05a51f.png)
![2021-09-24_16-43-38](https://user-images.githubusercontent.com/50781959/134662216-abf8b056-55b0-4002-aad6-8833b63c73d6.png)
![Uploading 2021-09-24_16-43-55.png…]()
![2021-09-24_16-45-01](https://user-images.githubusercontent.com/50781959/134662306-0248d3a2-41fa-4827-881c-83f0742afb91.png)

**Comment by Maria-Bordunova** [comment]
Hi @samatzhusup . You shouldn't use products from the `launch()` method. Please check the details for displaying products [here](https://documentation.qonversion.io/docs/displaying-products#displaying-products).
