### ISSUE TITLE
Sdk not initializing

### ISSUE THREAD

**Issue by ale-getman** [qonversion/flutter-sdk#12]
Hi team.

flutter doctor -v
[√] Flutter (Channel **stable**, v1.17.3, on Microsoft Windows [Version 10.0.18362.900], locale ru-RU)
    • Flutter version **1.17.3** at D:\flutter
    • Framework revision b041144f83 (2 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

version: **qonversion_flutter: ^0.2.5**

Tried each of these methods: launchWith, launchWithClientSideUserId, launchWithAutoTrackPurchases
But after the method is called, nothing comes back and the new user does not appear in the statistics.
In debug mode, I was able to reach the call of native functions, after them, nothing happens.

**Comment by iVirn** [comment]
> But after the method is called, nothing comes back and the new user does not appear in the statistics.

Hi! 
We've just published version 0.3.0 with API update, you can now use `launch` method to initialize Qonversion; all other methods have been deprecated. 
Please, try to update your SDK version and use new `launch` method to init Qonversion, we believe it should resolve existing problem.
