### ISSUE TITLE
Expose presentCodeRedemptionSheet

### ISSUE THREAD

**Issue by rwrz** [qonversion/flutter-sdk#126]

**Comment by Maria-Bordunova** [comment]
Hi @rwrz 
Could you please clarify your request?

**Comment by rwrz** [comment]
Sure.
On iOS, there is this method for the users to redeem offer codes. You guys already did the iOS SDK for it, just need to expose it on the Flutter SDK.

[Qonversion docs link.](https://documentation.qonversion.io/docs/appstore-offer-codes)

**Comment by Maria-Bordunova** [comment]
It is a great idea. Thanks for the suggestion! 
At the moment we can't estimate the details on when this will be implemented.  So let's keep in touch :raised_hands:

**Comment by SpertsyanKM** [comment]
The method `presentCodeRedemptionSheet` was added to [Qonversion release 4.6.0](https://github.com/qonversion/flutter-sdk/releases/tag/4.6.0)
