### ISSUE TITLE
MacOS - MissingPluginException(No implementation found for method purchaseProduct on channel qonversion_flutter_sdk)

### ISSUE THREAD

**Issue by oliverbytes** [qonversion/flutter-sdk#149]
Other APIs work except this `Qonversion.purchaseProduct()` function on MacOS

**Comment by suriksarkisyan** [comment]
Hi, @oliverbytes 
I've just checked that problem. We will fix and release a new version ASAP; already working on that. I'll come back when the fix is released.

**Comment by SpertsyanKM** [comment]
Forgot to mention that we had [released](https://github.com/qonversion/flutter-sdk/releases/tag/4.3.3) the fix three weeks ago.
