### ISSUE TITLE
ANR com.qonversion.android.sdk.FacebookAttribution.getAttributionId Input dispatching timed out

### ISSUE THREAD

**Issue by fleoparra** [qonversion/flutter-sdk#209]
Hello. My apps for Android are showing me this ARN with a lot of users affected (is less than 1% but is the ANR with more affected users in my case):

qonversion_flutter: ^5.1.0

On Play Console (Android vitals section):
> com.qonversion.android.sdk.FacebookAttribution.getAttributionId
> Input dispatching timed out

On Crashlytics:

> FacebookAttribution.java
> com.qonversion.android.sdk.FacebookAttribution.getAttributionId 

> main (native):tid=1 systid=9761 
> #00 pc 0xd6b94 libc.so (__ioctl + 4)
> #01 pc 0x936c4 libc.so (ioctl + 156)
> #02 pc 0x51a7c libbinder.so (android::IPCThreadState::talkWithDriver(bool) + 296)
> #03 pc 0x52a68 libbinder.so (android::IPCThreadState::waitForResponse(android::Parcel*, int*) + 60)
> #04 pc 0x527d8 libbinder.so (android::IPCThreadState::transact(int, unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 184)
> #05 pc 0x4b01c libbinder.so (android::BpBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 188)
> #06 pc 0x12b19c libandroid_runtime.so (android_os_BinderProxy_transact(_JNIEnv*, _jobject*, int, _jobject*, _jobject*, int) + 152)
>        at android.os.BinderProxy.transactNative(BinderProxy.java)
>        at android.os.BinderProxy.transact(BinderProxy.java:540)
>        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5945)
>        at android.app.ActivityThread.acquireProvider(ActivityThread.java:7138)
>        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2954)
>        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2509)
>        at android.content.ContentResolver.query(ContentResolver.java:1181)
>        at android.content.ContentResolver.query(ContentResolver.java:1128)
>        at android.content.ContentResolver.query(ContentResolver.java:1084)
>        at com.qonversion.android.sdk.FacebookAttribution.getAttributionId(FacebookAttribution.java)
>        at com.qonversion.android.sdk.QUserPropertiesManager.sendFacebookAttribution(QUserPropertiesManager.java)
>        at com.qonversion.android.sdk.Qonversion.launch(Qonversion.java)
>        at io.qonversion.sandwich.QonversionSandwich.launch(QonversionSandwich.java)
>        at com.qonversion.flutter.sdk.qonversion_flutter_sdk.QonversionFlutterSdkPlugin.launch(QonversionFlutterSdkPlugin.java)
>        at com.qonversion.flutter.sdk.qonversion_flutter_sdk.QonversionFlutterSdkPlugin.onMethodCall(QonversionFlutterSdkPlugin.java)
>        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java)
>        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java)
>        at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java)
>        at io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$TsixYUB5E6FpKhMtCSQVHKE89gQ(DartMessenger.java)
>        at io.flutter.embedding.engine.dart.DartMessenger$$InternalSyntheticLambda$0$ceffc6bae7d364cb48afaf1aaebd60bf9050360d0efb9035ebc54f0851df0a05$0.run(DartMessenger.java)
>        at android.os.Handler.handleCallback(Handler.java:938)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at android.os.Looper.loop(Looper.java:236)
>        at android.app.ActivityThread.main(ActivityThread.java:8037)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

My flutter doctor:

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 3.7.3, on macOS 13.2.1 22D68 darwin-arm64, locale es-CO)
> [✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
> [✓] Xcode - develop for iOS and macOS (Xcode 14.2)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2022.1)
> [✓] VS Code (version 1.75.1)
> [✓] Connected device (2 available)
> [✓] HTTP Host Availability
> 
> • No issues found!
>

**Comment by SpertsyanKM** [comment]
Hello! Thank you for your report! We will investigate your problem and return as soon as we have any info.

**Comment by SpertsyanKM** [comment]
We have released a new SDK version [5.2.0](https://github.com/qonversion/flutter-sdk/releases/tag/5.2.0) with the fix of the described issue. Please, update your dependency version to get rid of this problem. 

Thank you for your report and sorry for the late reply. Feel free to contact us if you have any questions!
