### ISSUE TITLE
BUG: call to userInfo() with null "identityId" throws exception (user.g.dart:12:24) - v5.1.0

### ISSUE THREAD

**Issue by royston-c** [qonversion/flutter-sdk#210]
I'm seeing an error when trying to call `userInfo()`. The generated JSON parsing for the User object tries to cast the  value of `identityId` in the JSON response to a string. If this value is `null` an execption is thrown and no userinfo object is returned.

https://github.com/qonversion/flutter-sdk/blob/c129fb402f58c7693ad391f89815bcba301ceb4a/lib/src/dto/user.g.dart#L9-L13

Stack trace:
```
0      _$QUserFromJson (package:qonversion_flutter/src/dto/user.g.dart:12:24)
1      new QUser.fromJson (package:qonversion_flutter/src/dto/user.dart:16:7)
2      QMapper.userFromJson (package:qonversion_flutter/src/internal/mapper.dart:50:18)
3      QonversionInternal.userInfo (package:qonversion_flutter/src/internal/qonversion_internal.dart:191:28)
<asynchronous suspension>
4      SubscriptionService._launch (package:app/core/services/subscriptions/subscription_service.dart:109:20)
<asynchronous suspension>
5      SubscriptionService.init (package:app/core/services/subscriptions/subscription_service.dart:46:5)
<asynchronous suspension>
```

**Comment by SpertsyanKM** [comment]
Hello! Thank you for your report and sorry for the late reply. 

This problem seems to occur in apps using Dart version 2.12.0+ which enables null-safety checks. We will fix this error in the next release.

**Comment by SpertsyanKM** [comment]
Happy to introduce the new [release version 5.2.0](https://github.com/qonversion/flutter-sdk/releases/tag/5.2.0), containing the fix of the described problem. 

Thank you again for your report!
