### ISSUE TITLE
 I am getting this error for calling collectApplesearchAds method

### ISSUE THREAD

**Issue by sparkmobi** [qonversion/flutter-sdk#220]
Hello 

while implementing qonversion in my app i started to see this error after adding collectAppleSearchads method

> [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(NoNecessaryDataError, Could not find necessary arguments, Make sure you pass correct call arguments, null)
#0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
<asynchronous suspension>

**Comment by pixelfoxxx** [comment]
Hello @sparkmobi. Thank you for contacting us and providing the detailed report. We found the issue on our side and fixed it. The release with the fix will be published soon. Please update to the latest SDK version after that. 

Let us know if you have any further questions. We'll be glad to assist!

**Comment by SpertsyanKM** [comment]
Hello, @sparkmobi. The new version of [Flutter SDK 5.3.1](https://github.com/qonversion/flutter-sdk/releases/tag/5.3.1) with the fix has been published. It will be available in several minutes. 

Thank you for your report!
