### ISSUE TITLE
Getting "A data connection is not currently allowed" error on iOS

### ISSUE THREAD

**Issue by sparkmobi** [qonversion/flutter-sdk#224]
hello 

i am getting this error 

> QonversionInternal.checkEntitlements
[FlutterError - PlatformException(-1020, A data connection is not currently allowed., Qonversion Error Code: -1020, null). Error thrown null.]

from my error understanding is that because there is no connection but in qonversion offline sdk documentation it said that it will return the last user entitlements cache

**Comment by SpertsyanKM** [comment]
Hello! Could you please provide us with a steps to reproduce your issue? Also please write which SDK version do you use.

If you could provide us with a minimal reproducible example - it would be even perfect.

**Comment by sparkmobi** [comment]
I am using qonversion sdk 5.3.1

here is a snippet from you code 

>     final Map<String, QEntitlement> entitlements =
    await Qonversion.getSharedInstance().checkEntitlements();

    isSubscribed = PurchasesUtils().checkUserSubscribed(entitlements);

` bool checkUserSubscribed(Map<String, QEntitlement> entitlements) {
    final premium = entitlements['premium'];
    if (premium != null && premium.isActive) {
      return true;
    } else {
      return false;
    }
  }`

**Comment by SpertsyanKM** [comment]
Do you face this problem on every call? 

Also, as far as I understood, you try to fetch entitlements without the internet connection?

**Comment by sparkmobi** [comment]
No, 

i am not facing this error, but this error is in my Firebase Analytics happens to some of my users

**Comment by SpertsyanKM** [comment]
Could you please clarify is it a platform specific issue or does it occur on both Android and iOS?

**Comment by sparkmobi** [comment]
ios

**Comment by sparkmobi** [comment]
![image](https://user-images.githubusercontent.com/2973369/229978804-18be8679-138a-40e2-8887-ede8b9d508e3.png)

**Comment by SpertsyanKM** [comment]
Thank you for the provided information! We will check this issue and write back as soon as we have any information.

**Comment by MathieuAlphamosa** [comment]
Same issue here.
iPhone 11 Pro - iOS 16.4.1

```
Crashed in non-app: message_codecs.dart in StandardMethodCodec.decodeEnvelope within flutter
qonversion_internal.dart in QonversionInternal.checkEntitlements at line 163 within qonversion_flutter

PlatformException: PlatformException(-1020, A data connection is not currently allowed., Qonversion Error Code: -1020, null)
```

**Comment by SpertsyanKM** [comment]
Could you please share any details and steps to reproduce that you have? 

I've tried to reproduce the crash multiple times playing with the internet connection, but all my attempts were unsuccessful.
