### ISSUE TITLE
Restore String Bug after Upgrading Conversion Version

### ISSUE THREAD

**Issue by FantaMagier** [qonversion/flutter-sdk#287]
Hey after upgrading the Qonversion package (qonversion_flutter: ^7.3.0) to the newest package the following error occurs on Android after Restoring:

```
[error] Uncaught Platform Error
_TypeError (type '_Map<Object?, Object?>' is not a subtype of type 'String?')
 #0      QonversionInternal.restore (package:qonversion_flutter/src/internal/qonversion_internal.dart:184:49)
                       <asynchronous suspension>
```

```dart
 await Qonversion.getSharedInstance().restore().then((value) {
            Map<String, QEntitlement> map = value;
            bool proActive = map["Pro"]?.isActive ?? false;
```

**Comment by suriksarkisyan** [comment]
Hi, @FantaMagier 
Thanks for the issue. I'll check ASAP and come back with an update.

**Comment by suriksarkisyan** [comment]
@FantaMagier could you please update our SDK to version [7.3.1](https://github.com/qonversion/flutter-sdk/releases/tag/7.3.1) and test again?

**Comment by FantaMagier** [comment]
@suriksarkisyan Thanks for you work!

**Comment by mpdevelopment39** [comment]
> @suriksarkisyan I have an issue with Flutter SDK a mapping error occurs when I call the restore function, even though I have updated the SDK version to 7.3.1.
> 
> ```
> final Map<String, QEntitlement> entitlements =
> await Qonversion.getSharedInstance().restore();
> ```
> 
> The error message is:
> 
> `Error: type '_Map<Object?, Object?>' is not a subtype of type 'String?'`
> 
> This error only happens on iOS devices.

Same problem here. I just implemented this call just after to identify my user on qonversion:

`await Qonversion.getSharedInstance().restore();`

With the latest version (7.3.1) i am receiving this error (Only on iOS):

`Error: type '_Map<Object?, Object?>' is not a subtype of type 'String?'`

But with a previous version like 7.2.0 the error message that i am receiving(Only on iOS too) is:

`{null, PlatformException(0, An unknown error has occurred, Qonversion Error Code: 0, null)}`
