### ISSUE TITLE
Mapping Error During Restore on iOS

### ISSUE THREAD

**Issue by aldiFoodLama** [qonversion/flutter-sdk#291]
I have an issue with Flutter SDK a mapping error occurs when I call the restore function, even though I have updated the SDK version to 7.3.1.

```
final Map<String, QEntitlement> entitlements = await Qonversion.getSharedInstance().restore();
```

The error message is:

`Error: type '_Map<Object?, Object?>' is not a subtype of type 'String?'`

This error only happens on iOS devices.

**Comment by mpdevelopment39** [comment]
@aldiFoodLama One question about your implementation :)

Where you are calling the restore method? Didn't you have any problems with that before update to latest sdk version?

When i call `await Qonversion.getSharedInstance().restore();` i am receiving this error:

_{null, PlatformException(0, An unknown error has occurred, Qonversion Error Code: 0, null)}_

But this only occurs in iOS, on Android it's working correctly.

Thank u ;)

**Comment by suriksarkisyan** [comment]
Hi, guys!
I apologize for the inconvenience! The fix has just landed! Could you please update it to [7.3.2](https://github.com/qonversion/flutter-sdk/releases/tag/7.3.2) and test it again?

**Comment by mpdevelopment39** [comment]
I just test with latest version 7.3.2 and my error continue.

![Captura de pantalla 2024-01-17 a las 17 47 15](https://github.com/qonversion/flutter-sdk/assets/35668151/547222de-c7a8-4b3a-b1bf-55ddaf510e4f)

This is my implementation. I just calling restore after identify my user on qonversion.

But i am receiving this error.

**Comment by aldiFoodLama** [comment]
Thank you, @suriksarkisyan, there are no mapping errors now.

**Comment by aldiFoodLama** [comment]
@mpdevelopment39  Maybe try running 'flutter clean' or attempt to reinstall pod dependencies.

**Comment by aldiFoodLama** [comment]
> @aldiFoodLama One question about your implementation :)
> 
> Where you are calling the restore method? Didn't you have any problems with that before update to latest sdk version?
> 
> When i call `await Qonversion.getSharedInstance().restore();` i am receiving this error:
> 
> _{null, PlatformException(0, An unknown error has occurred, Qonversion Error Code: 0, null)}_
> 
> But this only occurs in iOS, on Android it's working correctly.
> 
> Thank u ;)

@mpdevelopment39  Similar to yours, after call identify, I call the restore function. However, the restore function is manually invoked based on user interactions.
