### ISSUE TITLE
can't even flutter pub get this code.  update it.

### ISSUE THREAD

**Issue by sgehrman** [qonversion/flutter-sdk#309]
Because qonversion_flutter depends on build_runner >=0.1.1 <2.0.0 which doesn't support null safety, version solving failed.

The lower bound of "sdk: '>=1.9.1 <3.0.0'" must be 2.12.0 or higher to enable null safety.
For details, see https://dart.dev/null-safety

The lower bound of "sdk: '>=2.3.0 <3.0.0'" must be 2.12.0'
or higher to enable null safety.

The current Dart SDK (3.3.0) only supports null safety.

For details, see https://dart.dev/null-safety
exit code 65

--

[example] flutter pub get --no-example
Resolving dependencies...
The lower bound of "sdk: '>=2.3.0 <3.0.0'" must be 2.12.0'
or higher to enable null safety.

The current Dart SDK (3.3.0) only supports null safety.

For details, see https://dart.dev/null-safety
exit code 65

**Comment by SpertsyanKM** [comment]
Hello! Sorry for the late reply. We will check your issue and return as soon as we have any news.

**Comment by SpertsyanKM** [comment]
Hello! I'm happy to announce that we've released version 9.1.1 of the SDK with the sample app upgrade. Now the issue should be gone.

Thank you for bringing this to our attention!
