### ISSUE TITLE
JSON Parsing Error with RemoteConfig

### ISSUE THREAD

**Issue by FantaMagier** [qonversion/flutter-sdk#310]
I call up RemoteConfig as usual and this error currently appears:

[error] Uncaught Platform Error
[sentry.platformError] _TypeError (type 'Null' is not a subtype of type 'String' in type cast)
[sentry.platformError] #0      _$QRemoteConfigurationSourceFromJson (package:qonversion_flutter/src/dto/remote_configuration_source.g.dart:19:24)
                       #1      new QRemoteConfigurationSource.fromJson (package:qonversion_flutter/src/dto/remote_configuration_source.dart:41:7)
                       #2      _$QRemoteConfigFromJson (package:qonversion_flutter/src/dto/remote_config.g.dart:15:32)
                       #3      new QRemoteConfig.fromJson (package:qonversion_flutter/src/dto/remote_config.dart:28:7)
                       #4      QMapper.remoteConfigFromJson (package:qonversion_flutter/src/internal/mapper.dart:70:26)
                       #5      QonversionInternal.remoteConfig (package:qonversion_flutter/src/internal/qonversion_internal.dart:180:28)
                       <asynchronous suspension>
                       #6      RemoteConfigNotifer.loadRemoteConfig (package:histamin_scanner/Provider/remote_config_notifer.dart:9:26)
                       <asynchronous suspension>

**Comment by suriksarkisyan** [comment]
Hi @FantaMagier 
Could you please clarify what version of SDK you are using?

**Comment by FantaMagier** [comment]
qonversion_flutter: ^8.2.0

**Comment by suriksarkisyan** [comment]
> Hi @suriksarkisyan qonversion_flutter: ^8.2.0
> 
> And I am using an Android Emulator

Could you please provide step-by-step instruction? I'm trying to reproduce the issue but still no result.

**Comment by FantaMagier** [comment]
I am using this code:
```dart
Qonversion.getSharedInstance().remoteConfig().then((value) {
Navigator.pushNamed(context, '/paywall');
});
```

**Comment by suriksarkisyan** [comment]
> I am using this code:
> 
> ```dart
> Qonversion.getSharedInstance().remoteConfig().then((value) {
> Navigator.pushNamed(context, '/paywall');
> });
> ```

Please send me your company name and the app name or project key so I can check the remote configuration and try to reproduce the issue. I'm using the same code but haven't faced any problems.
Don't share that info here. Please send it to this email s.sarkisyan@qonversion.io

**Comment by FantaMagier** [comment]
@suriksarkisyan sent you a mail

**Comment by FantaMagier** [comment]
I have the same error on iOS and it shows this as well as this error:

![image](https://github.com/qonversion/flutter-sdk/assets/21313268/0425b6b6-9b69-49ab-8e9f-0adeb0e57d43)

**Comment by SpertsyanKM** [comment]
Thank you for the additional information! Could you please also clarify, how often this crash happens? Do your production users face it?

**Comment by FantaMagier** [comment]
It also seems to affect production. In addition, the other error message sometimes occurs and only with iOS so far. Really a strange bug. I hope you find the error, because the data is no longer loaded correctly from the RemoteConfig.

**Comment by FantaMagier** [comment]
Hi, it happens every time RemoteConfig is called. Do you mean with Identifier the Qonversion UID?

**Comment by SpertsyanKM** [comment]
Yes, Qonversion user ID. You can get it by `Qonversion.userInfo` call

**Comment by FantaMagier** [comment]
Android: QON_5baaa178b6964e51a275c09979e88e18

iOS: QON_ff3d38646ec5481e98b76930c09c4cc3

**Comment by SpertsyanKM** [comment]
Thanks! We will try to reproduce your issue again with this information.

**Comment by FantaMagier** [comment]
Maybe this is helpful from Sentry:

exception
_TypeError: type 'Null' is not a subtype of type 'String' in type cast
Error
14:34:37
http
GET https://api.qonversion.io/v3/remote-config [200]

{
http.query: user_id=QON_c8b2b22012294748a72b042f905cb167&context_key=,
reason: no error,
request_body_size: 0,
response_body_size: 2214
}
Info
14:34:37
http
POST https://api.qonversion.io/v1/user/init [200]

{
reason: no error,
request_body_size: 7044,
response_body_size: 2344
}
Info
14:34:37
device.connectivity

{
connectivity: wifi
}
Info
14:34:36
started
Breadcrumb Tracking

**Comment by SpertsyanKM** [comment]
Well, I've tried again and still couldn't reproduce - everything works fine even if I use the same user you've provided. 

To continue the investigation I'll have to ask you for a project with a minimal reproducible example. Could you please provide us with it as all our attempts to reproduce that crash were unsuccessful?
