### ISSUE TITLE
Many issues on example code

### ISSUE THREAD

**Issue by Huoran559** [qonversion/flutter-sdk#323]
1、flutter pub get since low vesion
 % flutter pub get
Resolving dependencies... 
The lower bound of "sdk: '>=2.3.0 <3.0.0'" must be 2.12.0'
or higher to enable null safety.

The current Dart SDK (3.4.0-220.0.dev) only supports null safety.

2、FlatButton is not defined 
3、The return type 'Null' isn't a 'QEntitlement'
4、Why dependency firebase?
5、Cloud you please provide a demo gif for your example?

**Comment by SpertsyanKM** [comment]
Hello! Thank you for reporting these issues. I apologize for the delayed response.

You're right, the sample app does need updates. We have put these fixes into our backlog.

Rest assured, we are working on addressing this. We appreciate your report and feedback, as it helps us improve our SDK.

**Comment by SpertsyanKM** [comment]
I’m excited to share that at the end of August, we launched [a new version](https://github.com/qonversion/flutter-sdk/releases/tag/9.1.1) of our Flutter SDK! This update includes an upgraded sample app that now utilizes the latest versions of Dart and Flutter, complete with support for null safety.
