### ISSUE TITLE
HTTP 500 Code 

### ISSUE THREAD

**Issue by FantaMagier** [qonversion/flutter-sdk#329]
With the Flutter SDK sometimes some user a get a io error with a HTTP 500 Repsonse but their have a internation Connection. The Method: qonversion_internal.dart in QonversionInternal.remoteConfig
 and get the following Error: 

PlatformException: PlatformException(NetworkConnectionFailed, There was a network issue. Please make sure that the Internet connection is available on the device, Unable to resolve host "api.qonversion.io": No address associated with hostname, null)

or PlatformException: PlatformException(-1009, Es besteht anscheinend keine Verbindung zum Internet., Qonversion Error Code: -1009, null)

I think the users have an Internet connection, otherwise they couldn't send the Sentry Crash Report.

 I am using the newest Qonversion Flutter SDK

```dart
class RemoteConfigNotifer extends StateNotifier<QRemoteConfig?> {
  RemoteConfigNotifer() : super(null);

  void loadRemoteConfig() async {
    final remoteConfig = await Qonversion.getSharedInstance().remoteConfig();

    state = remoteConfig;
    gRemoteConfig = remoteConfig;
  }
}

final remoteConfigProvider = StateNotifierProvider<RemoteConfigNotifer, QRemoteConfig?>(
  (ref) => RemoteConfigNotifer(),
);

```

**Comment by suriksarkisyan** [comment]
Hi, @FantaMagier 
NetworkConnectionFailed error is our wrapper above Android OS and Google Billing errors that indicate problems with the internet connection. I mean, we have no additional logic there; we just proxy the internet connection error from the system.
