### ISSUE TITLE
Crash with casting timestamp

### ISSUE THREAD

**Issue by andart** [qonversion/flutter-sdk#36]
Hello,
updated flutter sdk to 2.0.0 and iOS pod Qonversion (2.4.1) detect problem with casting property `QNLaunchResult.timestamp` to NSUInteger

<img width="1016" alt="Снимок экрана 2020-12-21 в 00 29 32" src="https://user-images.githubusercontent.com/17906338/102724918-06638080-4324-11eb-87db-f3d68174ab9b.png">

because of this I have a crash app in Xcode 11.7
<img width="1040" alt="Снимок экрана 2020-12-21 в 00 33 14" src="https://user-images.githubusercontent.com/17906338/102724956-3b6fd300-4324-11eb-925a-9d9f63a7f184.png">

**Comment by smejl** [comment]
HI @andart. Thanks for your report. We will check and come back asap.

**Comment by iVirn** [comment]
Hi again, @andart! 
We've just released version 2.0.1 with a fix of this bug. 
Please, update SDK version and everything should run nice and smooth:)

**Comment by andart** [comment]
checked latest release, all works good, thanks a lot
