### ISSUE TITLE
Incorrect call in method adjustUserID (QNDevice.m) leads to an exception

### ISSUE THREAD

**Issue by VeryazovSergey** [qonversion/flutter-sdk#360]
Hello! 

Using packages:
  qonversion_flutter: ^9.1.3
  adjust_sdk: ^5.0.2 

App crashes after 5 sec with exception:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[Adjust adid]: unrecognized selector sent to class 0x102b43770'
*** First throw call stack:
(0x19f810f20 0x1976bf2b8 0x19f91a328 0x19f7adfb4 0x19f7ad8d0 0x103211144 0x103235a38 0x19e6eb818 0x19f844a2c 0x19f8446d0 0x19f84422c 0x19f7e0888 0x19f7dfcd8 0x1e422d1a8 0x1a1e19ae8 0x1a1ecdd98 0x100d7c124 0x1c2fb7154)
libc++abi: terminating due to uncaught exception of type NSException
Type: stdio

Problem is in the file QNDevice.m, this method:

- (nullable NSString *)adjustUserID {
  Class Adjust = NSClassFromString(@"Adjust");
  SEL adid = NSSelectorFromString(@"adid");
  if (Adjust && adid) {
    id (*imp1)(id, SEL) = (id (*)(id, SEL))[Adjust methodForSelector:adid]; ///HERE
    NSString *adidString = nil;
    if (imp1) {
      adidString = imp1(Adjust, adid);
    }
    return adidString;
  }

  return nil;
}

Looks like they changed the method of getting id in Adjust. And you call it old way.

In my case I just commented that lines (to return nil) and all works now. (I get AdjustId my way and send it to Qonversion later)
But it have to be fixed.

Also I found that it happened deep in the **collectIntegrationsDataInBackground** method, and there is no way to affect it (setup/disable/etc) 

Thanks

**Comment by SpertsyanKM** [comment]
Hi @VeryazovSergey, thanks for bringing this to our attention. We’ll look into it and resolve the issue as quickly as we can.

**Comment by suriksarkisyan** [comment]
Hi, @VeryazovSergey 
Yes, you are right. The issue is related to the fact that the public interface in the new version of Adjust has changed. We will make the fix on our side and will inform you when it is released.

**Comment by suriksarkisyan** [comment]
Hi, @VeryazovSergey 
Thank you once again for the issue. We have released a new version [9.1.4](https://github.com/qonversion/flutter-sdk/releases/tag/9.1.4) with a fix for the problem. Please check if possible and let us know if everything is working correctly.

**Comment by suriksarkisyan** [comment]
@VeryazovSergey thanks a lot!
