### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by hasimyerlikaya** [qonversion/flutter-sdk#369]
Hi,
I'm implementing the Qonversion Flutter SDK into my project. I have a few questions.

**Question 1:**
I have two products with trial offers:

Annually with 14-day trial offer
Six Months with 7-day trial offer

I set these settings for both the Apple App Store and Google Play.

Do I need to specify the details of the offer if I use [the purchaseProduct](https://documentation.qonversion.io/docs/making-purchases#1-make-a-purchase) method?
If I don't define a specific offer ID, does Qonversion Flutter SDK get the related offer details from the product?

**Question 2:**
What error codes are returned when an error occurs during [the restore purchase](https://documentation.qonversion.io/docs/making-purchases#6-restore-purchases) process on Flutter? 
I couldn’t find this information in the documentation. I would appreciate it if you could clarify.

**Comment by hasimyerlikaya** [comment]
Hi @SpertsyanKM,

There is at most one offer tied to the selected product. I think the offer to be chosen will also be that one.
It’s nice that I won’t have to do anything different for Android and iOS.

My application uses Adapty for now. I saw Qonversion recently, and I liked it.
Your Flutter SDK is great. Models are well structured and documented. 
If everything goes well, I will publish a new version with Qonversion and recommend it to the other Flutter developer.

Thank you very much.

**Comment by hasimyerlikaya** [comment]
Actually, I have one more question. I was looking at [the Qonversion SDK Errors Details page](https://documentation.qonversion.io/docs/handling-errors). It shows different error codes for iOS and Android.

I didn’t fully understand how it works for Flutter projects. Do I need to check these error codes separately for iOS and Android? Is there a common error list/enum for Flutter?

**Comment by SpertsyanKM** [comment]
Yes, you can find the complete list of Flutter error codes in [the QErrorCode enum](https://github.com/qonversion/flutter-sdk/blob/develop/lib/src/dto/qonversion_error_code.dart)

**Comment by SpertsyanKM** [comment]
You are welcome!
