### ISSUE TITLE
Even though the expiration date has passed, the entitlement appears to be active

### ISSUE THREAD

**Issue by hasimyerlikaya** [qonversion/flutter-sdk#370]
Hi,

I have a trial package purchased through the App Store. During a test on an Android device, I encountered an issue.
Even though the purchased product has expired, it still returns `isActive=true`.
Shouldn’t it return `isActive=false `instead?

![image](https://github.com/user-attachments/assets/62669c4c-01aa-45c4-9786-fecdf0b3e6dc)

**Comment by SpertsyanKM** [comment]
Hi @hasimyerlikaya,

You’re right — it should update. However, we don’t refresh this field during the session, because its duration is relatively short compared to the subscription length in production (compared to the minutes in testing), making it unlikely for a subscription to expire while the session is active. If you restart your app, you’ll notice that the isActive flag will change.

Just so you know, we’re planning to revise this logic soon to avoid any confusion during testing.

**Comment by hasimyerlikaya** [comment]
@SpertsyanKM Thank you for replying. 
I realized that after the issue. It is fine, not a problem.

If it’s not a problem, I have one more question.

I am testing the scenario where a user deletes their account while having an active subscription and then creates a new account.

Here’s the situation:

Identity UID: 1
User Email Property: one@one.com

This user has purchased subscriptions and has past payments. I can see this on the Customer screen, along with the entire transaction history (including payments made via Adapty).

The user deletes their account and creates a new one:

Identity UID: 2
User Email Property: one@one.com

In the Qonversion panel, this second customer is created, but the previous transaction history is not transferred to this customer.

As a result, there are now two customers with the same email address.
	•	If I search for the customer using Identity UID=2, I can find the customer, but no transactions are displayed.
	•	If I search by email, I find the first customer, but this user has been deleted in my system, and Identity UID=1 is no longer valid.

Can I fix this using the Transfer Entitlement option in the Entitlement settings, or is there another way?

The main issue is this:
When the second (new) user purchases a package, the purchased packages still appear in the transaction history of the first (deleted) user in the Qonversion system.

I hope I was able to explain it clearly. :)

**Comment by SpertsyanKM** [comment]
Your situation is straightforward. In our system, each identity corresponds to a different user. When you authorize a user with a new identity, we create a separate user account and link it to that identity. The original account stays intact, and all subscription renewals will continue to be associated with it since the original purchase transaction is tied to that account.

Regarding the email address, it's just a user property. User properties aren’t required to be unique, so the same email can be associated with multiple users.

The option to [transfer entitlements](https://documentation.qonversion.io/docs/transferring) is specifically for restoring requests.

**Comment by hasimyerlikaya** [comment]
Frankly, this was something I did not expect. When I called the `identify` method, I thought it would match the old account with the new ID.

I carefully read the documentation screen about user identification. Offering subscriptions to users across multiple platforms requires some caution.

Here’s the issue for me: let’s say a user reports a problem with their subscription, and I want to check it. If the user has deleted their account and created a new one, they can still use their subscription. However, I might have trouble finding the corresponding subscription in the Qonversion management panel. This is because they now have a new ID and are considered a new user in your system. Since the subscriptions belong to the old user, I would need to search for that subscription via email or another method to check it.

I think it would make much more sense if the identify method linked the existing subscription to the new ID instead of creating a new user. Of course, I assume there are reasons for this design that I might not be aware of.

In this case, the new user created in your system has no real purpose. It’s essentially an empty user, and accessing it via the ID becomes meaningless.

If the user deletes their account again and re-registers or logs in with another account, they will still be able to access their subscriptions. However, a separate user will be created for each case.

My suggestion is to list these linked users under a single user profile as “connected accounts” and allow us to view all of them on a single screen.

This way, even if a user deletes their account, we can see their new accounts alongside their old accounts in one place and manage them better in your system.

**Customer with deleted account Id**
![image](https://github.com/user-attachments/assets/d5403588-25b0-4385-ad59-3ef6c468a7b6)

**Linked account with new Id**
![image](https://github.com/user-attachments/assets/58cc38f9-3679-4509-923d-57c8da7dd896)

**Comment by SpertsyanKM** [comment]
Identity flow is designed for cross-platform access management, allowing you to connect Qonversion users with your own identity systems. This means that when a user logs in on a different device, their associated Qonversion account can be loaded along with all their entitlements.

On that device, there might be another user with different entitlements and subscriptions. In such cases, if the newly logged-in user requests a restore, they will receive entitlements for the previously purchased subscriptions on that device — this is how app stores typically function. The restoration process we discussed earlier determines how Qonversion should handle the entitlements of the previous user: whether to keep them active or transfer them to the new user.

Now, when considering account deletion and re-registration, we must ask: is the newly registered account considered a new one? The answer depends on your logic. Based on your criteria, you might decide to use the same identity for the new registration. For instance, if your system uniquely identifies users by their email addresses, you can use the same email with Qonversion. Even if a user deletes their account and creates a new one with the same email, their Qonversion user profile will remain intact, including all history and subscriptions.

Conversely, if you view the new account as distinct, then there would be no reason to link it to the old account in Qonversion.

**Comment by hasimyerlikaya** [comment]
To fully understand how the system works, I conducted quite a few tests. And I believe I now have a better understanding of how your system operates.
	•	I have three different user accounts.
	•	Whichever of these three accounts is identified and creates a new order becomes the main account, and the user history is added to this account.
	•	The other two accounts gain subscription privileges after the identify method is called, but their subscription history doesn’t appear in the management panel.

I would like to see the user history on the pages of the linked accounts as well, or at least a way to access the main account they are linked to. Currently, this doesn’t seem possible in your system. However, I found a workaround:
	•	After logging in, I identify the user using the identify method.
	•	I take the transactionId value of the last item in the transaction list within the entitlements and add it as a custom property to the identified user’s account.

This way, I can search by the transactionId, find the main account associated with the linked account, and view the transaction history.
Although it’s a bit of a roundabout approach, I now have a way to access the main account through linked accounts.

I believe the QEntitlement class should also include “Qonversion UID” and “Identity UID” information. This would allow us to check which account the entitlement comes from. Based on my scenario, I could add these as custom properties to establish connections between accounts.

In the Customer Search panel, I encountered two issues:
	•	When I search by “Email,” I cannot see the user accounts.
	•	When I search with the “Custom User ID” field, it always returns the main account, regardless of the value I enter.

Could you please check these?

Lastly, I actually considered defining the user by their email address.
It seems like a good option. However, if the user changes their email address, the old email address would remain as the identity UID.

Would it be possible to add a function to update the identity UID?

**Comment by SpertsyanKM** [comment]
Your message raises some interesting questions about the product, including feature requests and bug reports for the dashboard. To address these effectively, I recommend reaching out through our support channel. Please click the icon in the bottom right corner of the dashboard to submit your inquiries. You can share the link to this issue to avoid repeating all the context.

My colleagues are best equipped to assist you with these issues, as this discussion isn’t the right fit for the SDK GitHub Issues page. Thank you!

**Comment by SpertsyanKM** [comment]
I’m really glad to hear that! Thank you for all your feedback. We truly appreciate you sharing your experience with us!
