### ISSUE TITLE
Migration from Adapty

### ISSUE THREAD

**Issue by hasimyerlikaya** [qonversion/flutter-sdk#373]
The latest version of my app uses Adapty, and my existing customers have purchased subscriptions through Adapty. With the new version, I will start using Qonversion, but I encountered an issue during testing.

Subscriptions purchased through Adapty cannot be recognized by Qonversion. Despite having an active subscription, Qonversion fails to detect it.

What steps do I need to take during the transition from Adapty to ensure existing users can continue using their subscriptions?
There is no page related to Adapty in the Migration section of the doc.

I would appreciate it if you could assist me with this matter.

**Comment by gorgeoussamq** [comment]
hi @hasimyerlikaya could you please drop an email to support@qonversion.io so we can discuss issues you have encountered and provide you with resolution steps?

**Comment by hasimyerlikaya** [comment]
Hi, we had a conversation through the email support, but I could not find a solution.
I have a subscription that I bought through Adapty, and it is active on my phone. I want to publish a new version with Qonversion, but I can't use my active subscription. If I publish a new version without migration, my current users won't be able to use the app. 

[In the migration doc, it says client side migration is possible. ](https://documentation.qonversion.io/docs/migrating-subscriptions)
After the initialization, I'm calling three functions.

```dart
  await AppSubscriptionManager.qonversion.syncHistoricalData();
  await AppSubscriptionManager.qonversion.syncPurchases();
  await AppSubscriptionManager.qonversion.syncStoreKit2Purchases();
```

I didn't get any error, but I didn't get any result either. 
I don't have any idea what these functions did because they don't have a return value.

I asked Adapty for migration files, but I don't know when they will provide them.
Now I can't publish the new version of my app because of migration.

**Comment by SpertsyanKM** [comment]
Hi @hasimyerlikaya,

If you have an active subscription for the store product linked to your Qonversion product, calling these functions should restore it and provide the user with the appropriate entitlements. You can verify this by using Qonversion.shared.checkEntitlements. If it doesn’t work, there might be an issue with the configuration. Here are a few things to check:

- The subscription may have expired.
- The store product might not be linked to any Qonversion product.
- There could be no entitlement associated with the Qonversion product.

**Comment by hasimyerlikaya** [comment]
Hi,

- My subscription is active. I can see the subscription with Adapty.

<img width="665" alt="image" src="https://github.com/user-attachments/assets/43d18b15-d4cf-490d-a9b6-3ceaf4b0c6b7" />
<br>

- I have the same entitlement (pro) and product ID on the Qonversation dashboard.
<img width="998" alt="image" src="https://github.com/user-attachments/assets/d55d99b0-5b7d-41c5-ab90-1fc2da8c2ab0" />

I have no idea why client-side migration is not working. The sync functions are not returning any error. How can we check these sync processes? Is there any way to check logs?

**Comment by gorgeoussamq** [comment]
Hi @hasimyerlikaya we have a support ticket opened, I suggest continuing our discussion there to make sure we can keep track of all diagnostic data and troubleshooting history
