### ISSUE TITLE
[bug] Invalid argument: Instance of 'QPurchaseUpdatePolicy'

### ISSUE THREAD

**Issue by AErmek** [qonversion/flutter-sdk#374]
My code from Qonversion Docs example:
```dart
var purchaseOptions = QPurchaseOptionsBuilder()
    .setOldProduct(oldProduct)
    .setUpdatePolicy(QPurchaseUpdatePolicy.chargeFullPrice)
    .build();
var entitlements = await Qonversion.getSharedInstance().purchaseProduct(
    product,
    purchaseOptions: purchaseOptions
);
```

only when i call `setUpdatePolicy` with any `QPurchaseUpdatePolicy`, i receive error: 

> Invalid argument: Instance of 'QPurchaseUpdatePolicy'

It think, the problem is in qonversion_internal.dart on 121 line, you are providing enum value instead of basic String value
```dart
Constants.kUpdatePolicyKey: purchaseOptions.updatePolicy
``` 
fix should be smth like:
```dart
final updatePolicy = purchaseOptions.updatePolicy;
...
Constants.kUpdatePolicyKey: updatePolicy != null
            ? StringUtils.capitalize(describeEnum(updatePolicy))
            : null,
...
```

**Comment by SpertsyanKM** [comment]
Hi @AErmek , 

Thank you for bringing this to our attention! That's really our fault. The fix will be released very soon.

**Comment by SpertsyanKM** [comment]
The new [version 9.2.1](https://github.com/qonversion/flutter-sdk/releases/tag/9.2.1) with the fix has just been released. Thank you again for reporting this bug! 

I'll go ahead and close this issue, but feel free to reopen it or create new ones if you have any further questions.
