### ISSUE TITLE
com.qonversion.io error 2. isUserCancelled: false

### ISSUE THREAD

**Issue by fabianogadenz** [qonversion/flutter-sdk#39]
Hello everyone, set up my project, cloned this the repository, modified the project id.
The product list is listing correctly, but the permissions are not listen. When I try to buy an item, I get this error:

`The operation couldn’t be completed. (com.qonversion.io error 2.), isUserCancelled: false`

I am developing on iOS debug mode, virtual device. Where can I search for a solution to this error 2?

**Comment by suriksarkisyan** [comment]
Hi @fabianogadenz 
Can you please use a real device? And let me know if the problem still occurs

**Comment by fabianogadenz** [comment]
yes, the problem persists in real device.
XCode: 12.3

https://imgur.com/a/ozMthAP
https://imgur.com/a/rmar2Bm

The test application only recognize the product, I cannot make the purchase. I have already reviewed all the settings according to the documentation and I cannot understand this error.

`The operation couldn’t be completed. (com.qonversion.io error 2.), isUserCancelled: false`

my flutter -doctor

`[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H15, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

• No issues found!`

**Comment by fabianogadenz** [comment]
I set up the apple product on the panel. I cloned the project from this repository, registered the project key and it doesn't work. Did I forget something?

**Comment by fabianogadenz** [comment]
a detail that I forgot to comment. I'm using a test that is in production and prohibiting the product for testing. Is there any problem?

**Comment by fabianogadenz** [comment]
my product status in Apple Store is Approved. at the moment, we are selling in production

**Comment by suriksarkisyan** [comment]
Hi, @fabianogadenz 
Let me check your configuration so I can try to give more useful information to you
I'll come back soon

**Comment by fabianogadenz** [comment]
Thanks for your response @suriksarkisyan,
I will attach some more information about the code, I believe it can help you.

<img width="559" alt="Screen Shot 2021-01-26 at 07 50 11" src="https://user-images.githubusercontent.com/12851596/105836135-875d0a00-5fab-11eb-98c9-3c26966d1b6b.png">
<img width="1074" alt="Screen Shot 2021-01-26 at 07 51 36" src="https://user-images.githubusercontent.com/12851596/105836146-8a57fa80-5fab-11eb-807b-26d00c16b02a.png">

**Comment by suriksarkisyan** [comment]
Hi @fabianogadenz
I see on your screen that the SKProduct is null.
Look's like you forgot to replace the project bundle id. It's impossible to download SKProducts for your identifiers with our bundle id. Just set your bundle id and try again. 🤞
