### ISSUE TITLE
Migration to null safety.

### ISSUE THREAD

**Issue by mrdemqn** [qonversion/flutter-sdk#60]
Hi!

I ran into a problem with the migration of my project to Null Safety Sound. Since the plugin does not support zero security.

Please tell me if plans for the migration of the plugin?

**Comment by Maria-Bordunova** [comment]
Hello, @mrdemqn ! 
Yes, we have the migrating to null safety in our plans. We expect it to be supported during the next 2 week. In case we add it earlier, we'll let you know either.

**Comment by mrdemqn** [comment]
> Hello, @mrdemqn !
> Yes, we have the migrating to null safety in our plans. We expect it to be supported during the next 2 weeks. In case we add it earlier, we'll let you know either.

Thanks for the answer.

**Comment by royston-c** [comment]
@Maria-Bordunova any update on null safety migration?

**Comment by Maria-Bordunova** [comment]
Hi , @royston-c . It is high priority for us right now. We are working on null safety migration at the moment. We faced with a problem, we didn't expect to. So, it takes more time. We expect it to be ready by the end of the week

**Comment by Maria-Bordunova** [comment]
Hi, @royston-c , @mrdemqn , @northelks
We've published flutter-sdk release 3.0.0 🐣. It supports null safety now.

**Comment by northelks** [comment]
Cool! Thank you :)
