### ISSUE TITLE
a question about Feature

### ISSUE THREAD

**Issue by kellvembarbosa** [qonversion/flutter-sdk#99]
Is it function available for those used to SDK Flutter?

https://camo.githubusercontent.com/e3d831faa1d41b52f828eac7372031345ea353bcd428e5b258c3ed941e806f0d/68747470733a2f2f716f6e76657273696f6e2e696f2f696d672f4032782f6175746f6d6174696f6e2f696e2d6170702d636f6e7374727563746f722e676966

**Comment by Maria-Bordunova** [comment]
Hi, @kellvembarbosa ! Thank for your question. For now Automation tool is available only on native SDKs (iOS, Android). But we have plans to support flutter as well.

Could you tell us please whether you use push notifications in your app? Or you are interested in showing in-app screens only?

**Comment by kellvembarbosa** [comment]
I use another platform, I found this feature interesting that I only met until now on your platform.

I hope soon to have this for flutter because I have total interest ...
